catalogMode: prefer
ignoreWorkspaceRootCheck: true
minimumReleaseAgeExclude:
  - '@types/node@25.9.0'
  - '@turbo/darwin-64@2.10.5'
  - '@turbo/darwin-arm64@2.10.5'
  - '@turbo/linux-64@2.10.5'
  - '@turbo/linux-arm64@2.10.5'
  - '@turbo/windows-64@2.10.5'
  - '@turbo/windows-arm64@2.10.5'
  - turbo@2.10.5
shellEmulator: true
trustPolicy: no-downgrade

packages:
  - packages/*

catalog:
  '@changesets/changelog-github': ^0.7.0
  '@changesets/cli': ^2.31.0
  '@clack/prompts': ^1.7.0

catalogs:
  cli:
    '@antfu/eslint-config': ^9.0.0
    eslint: ^10.4.0
    nano-staged: ^1.0.2
    simple-git-hooks: ^2.13.1
    skills-npm: ^1.1.1
    tsdown: ^0.22.0
    turbo: ^2.10.5
    typescript: ^6.0.3
  testing:
    vitest: ^4.1.6
  types:
    '@types/node': ^25.9.0

allowBuilds:
  esbuild: true
  simple-git-hooks: true
